export const LEADS_SUBMIT_REQUEST = "LEADS_SUBMIT_REQUEST";
export const LEADS_SUBMIT_SUCCESS = "LEADS_SUBMIT_SUCCESS";
export const LEADS_SUBMIT_FAIL = "LEADS_SUBMIT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
